---
images:
  lake0: "{{ lookup('env','APOLLO_APP_LAKE0_IMAGES_LAKE0') | default('registry.gitlab.com/peter.saarland/lake0:latest', true) }}"

restic_repository: "{{ lookup('env','RESTIC_REPOSITORY') | default('s3:https://minio.'+platform_domain+'/'+apollo_environment+'-backups', true) }}"
restic_password: "{{ lookup('env','RESTIC_PASSWORD') | default(admin_password, true) }}"
restic_backup_cron: "{{ lookup('env','RESTIC_BACKUP_CRON') | default('*/2 * * * *', true) }}"
restic_forget_args: "{{ lookup('env','RESTIC_FORGET_ARGS') | default('--prune --keep-last 10 --keep-hourly 24 --keep-daily 7 --keep-weekly 52 --keep-monthly 120 --keep-yearly 100', true) }}"

