---
- name: restart vmalert
  become: true
  systemd:
    daemon_reload: true
    name: vmalert
    state: restarted

- name: restart alertmanager
  become: true
  systemd:
    daemon_reload: true
    name: alertmanager
    state: restarted

- name: restart karma
  become: true
  systemd:
    daemon_reload: true
    name: karma
    state: restarted