---
# defaults file for zero-app-minio
images:
  wg_web: "{{ lookup('env','APOLLO_APP_WIREGUARD_IMAGES_WG_WEB') | default('vx3r/wg-gen-web:latest', true) }}"

wireguard_port: "5888"
wireguard_path: "/etc/wireguard"

wireguard_network_name: "private"

debian_enable_testing: true
debian_pin_packages: true

client_vpn_ip: ""
client_wireguard_path: "~/wg.conf"

wireguard_additional_peers: false
wireguard_post_up: false
wireguard_post_down: false