---

gitlab_runner_download_url: 'https://gitlab-runner-downloads.s3.amazonaws.com/{{ gitlab_runner_wanted_tag }}/binaries/gitlab-runner-darwin-amd64'

gitlab_runner_executable: "/usr/local/bin/{{ gitlab_runner_package_name }}"
