apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://trickster:9090
  isDefault: true
  version: 1
  editable: false