# from apollo.py
apollo_space_dir: "{{ lookup('env','APOLLO_SPACE_DIR') | default('/cargo', true) }}"
force_reboot: 0
become: "{{ False if ansible_facts['os_family'] == 'Windows' else True }}"
become_method: "{{ 'runas' if ansible_facts['os_family'] == 'Windows' else 'sudo' }}"
ansible_python_interpreter: '/usr/bin/python3'
ansible_ssh_private_key_file: "{{ lookup('env','SSH_PRIVATE_KEY_FILE') | default(apollo_space_dir+'/.ssh/id_rsa', true) }}"
ansible_ssh_public_key_file: "{{ lookup('env','SSH_PUBLIC_KEY_FILE') | default(apollo_space_dir+'/.ssh/id_rsa.pub', true) }}"

# from environment
in_ci: "{{ lookup('env','CI') | default(0, true) }}"
apollo_in_ci: "{{ lookup('env','CI') | default(in_ci, true) }}"

# from group_vars
apollo_space: "{{ arc['space']['name'] }}"
apollo_remote_dir: "/srv/.apollo"
apollo_app_dir: "{{ apollo_remote_dir+'/apps' }}"
apollo_addon_dir: "{{ apollo_remote_dir+'/addons' }}"
apollo_downloads_dir: "{{ apollo_remote_dir+'/downloads' }}"
apollo_volumes_dir: "{{ apollo_remote_dir+'/volumes' }}"
apollo_binary_dir: "/usr/local/bin"

# CHECK AGAIN
apollo_terraform_destroy: "{{ lookup('env', 'APOLLO_TERRAFORM_DESTROY') | default(0,true) }}"
apollo_data_nfs_source: "{{ hostvars[arc['data']['nfs_source']] }}"
apollo_data_nfs_directory: "{{ arc['data']['nfs_directory'] }}"

#####
#####
#####
#####
# TODO BELOW
####
####
####
# apollo. > PaaS > Backplane
# backplane_enabled: "{{ lookup('env','BACKPLANE_ENABLED') | default(1, true) }}"
# apollo_controlplane_enabled: "{{ lookup('env','APOLLO_CONTROLPLANE_ENABLED') | default(arc['controlplane']['enabled'], true) }}"
# apollo_backplane_enabled: "{{ lookup('env','APOLLO_BACKPLANE_ENABLED') | default(arc['backplane']['enabled'], true) }}"

# apollo. > PaaS > Apps
# zero_apps: "{{ lookup('env','ZERO_APPS').split(',') | default([''], true) }}"
# apollo_apps: "{{ lookup('env','APOLLO_APPS').split(',') | default(zero_apps, true) }}"
# app_healthcheck_retries: "{{ lookup('env','APOLLO_APP_HEALTHCHECK_RETRIES') | default(30, true) }}"
# app_healthcheck_delay: "{{ lookup('env','APOLLO_APP_HEALTHCHECK_DELAY') | default(30, true) }}"


# apollo. > PaaS > Apps > GitLab
#gitlab_shared_runners_token: "{{ lookup('env','GITLAB_SHARED_RUNNERS_TOKEN') | default('z7e3r2o0', true) }}"

# apollo. > PaaS > Apps > GitLab Runner
# runner_enabled: "{{ lookup('env','RUNNER_ENABLED') | default(arc['gitlab']['runner']['enabled'], true) }}"
# apollo_runner_enabled: "{{ lookup('env','APOLLO_RUNNER_ENABLED') | default(arc['gitlab']['runner']['enabled'], true) }}"
# apollo_gitlab_runner_enabled: "{{ lookup('env','APOLLO_GITLAB_RUNNER_ENABLED') | default(arc['gitlab']['runner']['enabled'], true) }}"
# runner_deploy_enabled: "{{ lookup('env','RUNNER_DEPLOY_ENABLED') | default(arc['gitlab']['runner']['deploy']['enabled'], true) }}"
# apollo_gitlab_runner_deploy_enabled: "{{ lookup('env','APOLLO_GITLAB_RUNNER_DEPLOY_ENABLED') | default(arc['gitlab']['runner']['deploy']['enabled'], true) }}"
# runner_build_enabled: "{{ lookup('env','RUNNER_BUILD_ENABLED') | default(arc['gitlab']['runner']['build']['enabled'], true) }}"
# apollo_gitlab_runner_build_enabled: "{{ lookup('env','APOLLO_GITLAB_RUNNER_BUILD_ENABLED') | default(arc['gitlab']['runner']['build']['enabled'], true) }}"
# runner_token: "{{ lookup('env','GITLAB_RUNNER_TOKEN') | default(arc['gitlab']['runner']['token'], true) }}"
# apollo_gitlab_runner_token: "{{ lookup('env','APOLLO_GITLAB_RUNNER_TOKEN') | default(arc['gitlab']['runner']['token'], true) }}"
# gitlab_runner_coordinator_url: "{{ arc['gitlab']['runner']['coordinator_url'] | default('https://gitlab.com', true) }}"
# apollo_gitlab_runner_coordinator_url: "{{ lookup('env','APOLLO_GITLAB_RUNNER_COORDINATOR_URL') | default(arc['gitlab']['runner']['coordinator_url'], true) }}"
# ci_docker_image: "docker:19.03.12"
# ci_dind_image: "docker:19.03.12-dind"
# runner_env: 
#     - "DOCKER_DRIVER=overlay2"
#     - "DOCKER_BUILDKIT=1"
# gitlab_runner_package_version: 13.3.1
# gitlab_runner_listen_address: "{{ apollo_cluster_ip }}:9252"
# gitlab_runner_registration_token: "{{ apollo_gitlab_runner_token }}"
# gitlab_runner_package_name: 'gitlab-runner'

    
# apollo. > PaaS > Integrations > GitLab
# gl_token: "{{ lookup('env','GL_TOKEN') }}"
# apollo_gitlab_token: "{{ lookup('env','APOLLO_GITLAB_TOKEN') | default(gl_token) }}"
# registry_url: "{{ lookup('env','GITLAB_REGISTRY_URL') | default('registry.gitlab.com', true) }}"
# apollo_gitlab_registry_url: "{{ lookup('env','APOLLO_GITLAB_REGISTRY_URL') | default(registry_url, true) }}"
# registry_user: "{{ lookup('env','GITLAB_REGISTRY_USER') }}"
# apollo_gitlab_registry_user: "{{ lookup('env','APOLLO_GITLAB_REGISTRY_USER') | default(registry_user) }}"
# registry_password: "{{ lookup('env','GITLAB_REGISTRY_PASSWORD') | default(apollo_gitlab_token, true) }}"
# apollo_gitlab_registry_password: "{{ lookup('env','APOLLO_GITLAB_REGISTRY_PASSWORD') | default(registry_password, true) }}"

# apollo_required_vars:
#     - apollo_base_domain
#     - apollo_ingress_ip
#     - apollo_management_ip
#     - apollo_space
#     - apollo_admin_user
#     - apollo_admin_password

# apollo. > Federation
# apollo_federation_dir: "{{ lookup('env','APOLLO_FEDERATION_DIR') | default('/tmp/federation', true) }}"
# apollo_federation_enabled: "{{ lookup('env','APOLLO_FEDERATION_ENABLED') | default(0, true) }}"
# apollo_federation_username: "{{ lookup('env','APOLLO_FEDERATION_USERNAME') | default('apollo-federation', true) }}"
# apollo_federation_password: "{{ lookup('env','APOLLO_FEDERATION_PASSWORD') | default('', true) }}"
# apollo_federation_spaces: "{{ lookup('env','APOLLO_FEDERATION_SPACES').split(',') | default([''], true) }}"

# apollo. > SMTP
# zero_smtp_server: "{{ lookup('env','ZERO_SMTP_SERVER') | default(apollo_manager, true) }}"
# apollo_smtp_server: "{{ lookup('env','APOLLO_SMTP_SERVER') | default(zero_smtp_server, true) }}"
# zero_smtp_username: "{{ lookup('env','ZERO_SMTP_USERNAME') | default('', true) }}"
# apollo_smtp_username: "{{ lookup('env','APOLLO_SMTP_USERNAME') | default(zero_smtp_username, true) }}"
# zero_smtp_password: "{{ lookup('env','ZERO_SMTP_PASSWORD') | default('', true) }}"
# apollo_smtp_password: "{{ lookup('env','APOLLO_SMTP_PASSWORD') | default(zero_smtp_password, true) }}"
# zero_smtp_port: "{{ lookup('env','ZERO_SMTP_PORT') | default('25', true) }}"
# apollo_smtp_port: "{{ lookup('env','APOLLO_SMTP_PORT') | default(zero_smtp_port, true) }}"
