ansible_ssh_private_key_file: "{{ lookup('env','SSH_PRIVATE_KEY_FILE') | default('.ssh/id_rsa', true) }}"
ansible_python_interpreter: "{{ lookup('env','PYTHON_INTERPRETER') | default('/usr/bin/python3', true) }}"
ntp_timezone: "{{ lookup('env','NTP_TIMEZONE') | default('Etc/UTC', true) }}"
locale_lang: "{{ lookup('env','LOCALE_LANG') | default('de_DE.UTF-8', true) }}"
pip_package: "{{ lookup('env','PIP_PACKAGE') | default('python3-pip', true) }}"
# Custom
ingress_ip: "{{ lookup('env','INGRESS_IP') | default('127.0.0.1', true) }}"
base_domain: "{{ lookup('env','BASE_DOMAIN') | default(ingress_ip + '.xip.io', true) }}"
admin_user: "{{ lookup('env','ADMIN_USER') | default('admin', true) }}"
admin_password: "{{ lookup('env','ADMIN_PASSWORD') | default('admin', true) }}"
# Cloudflare
cloudflare_enabled: "{{ lookup('env','CLOUDFLARE_ENABLED') | default(0, true) }}"
cloudflare_api_email: "{{ lookup('env','CLOUDFLARE_API_EMAIL') }}"
cloudflare_api_key: "{{ lookup('env','CLOUDFLARE_API_KEY') }}"
# Lets Encrypt
letsencrypt_mail: "{{ lookup('env','LETSENCRYPT_MAIL') }}"
# GitLab
# GitLab Personal Access token: https://gitlab.com/profile/personal_access_tokens
gl_token: "{{ lookup('env','GITLAB_GL_TOKEN') }}"
registry_url: "{{ lookup('env','GITLAB_REGISTRY_URL') | default('registry.gitlab.com', true) }}"
registry_user: "{{ lookup('env','GITLAB_REGISTRY_USER') }}"
registry_password: "{{ lookup('env','GITLAB_REGISTRY_PASSWORD') | default(gl_token, true) }}"
runner_token: "{{ lookup('env','GITLAB_RUNNER_TOKEN') | default('SUCHSECRETMUCHWOW', true) }}"
# Slack
slack_webhook: "{{ lookup('env','SLACK_WEBHOOK') }}"
slack_channel: "{{ lookup('env','SLACK_CHANNEL') }}"

# Kernel
kernel_update_grub_requested_kernel_version: 4.15.0-74-generic

# Storidge
storidge_enabled: "{{ lookup('env','STORIDGE_ENABLED') | default(0, true) }}"
storidge_version: "{{ lookup('env','STORIDGE_VERSION') | default('3107', true) }}"

ci_docker_image: "docker:19.03.5"
ci_dind_image: "docker:19.03.5-dind"
runner_env: 
    - "GL_TOKEN={{ gl_token }}"
    - "DOCKER_DRIVER=overlay2"
    - "DOCKER_BUILDKIT=1"

# Clouds
## IBM
ibm_cloud_enabled: "{{ lookup('env','IBM_CLOUD_ENABLED') | default(0, true) }}"

swarm_networks:
    - proxy
    - portainer
    - consul
    - monitoring
    - s3

