---
# tasks file for zero-app-portainer
- name: Provision Portainer
  block:
    - name: Copy Stack-File
      template:
        src: templates/docker-compose.yml.j2
        dest: /tmp/zero-app-portainer.yml
        owner: root
        group: root
        mode: '0644'

    - name: Provision Portainer
      docker_stack:
        state: present
        name: portainer
        prune: yes
        with_registry_auth: yes
        compose:
          - /tmp/zero-app-portainer.yml
      register: portainer_provision
      tags:
          - portainer

    - name: "Wait for http://portainer.{{ base_domain }} to become ready"
      uri:
        url: "http://portainer.{{ base_domain }}"
        method: GET
        status_code: 200
        validate_certs: no
      register: _result
      until: _result.status == 200
      retries: 30
      delay: 10
      tags:
        - portainer

    - name: Remove Stack File
      file:
        path: /tmp/zero-app-portainer.yml
        state: absent
  rescue:
    - name: Teardown Portainer
      docker_stack:
          absent_retries: 5
          absent_retries_interval: 10
          state: absent
          name: portainer
      register: portainer_portainer
    
    - name: Remove Stack File
      file:
        path: /tmp/zero-app-portainer.yml
        state: absent