---
# tasks file for zero-app-cadvisor
- name: Provision registry
  block:
    - name: Creating app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        owner: "apollo"
        group: "apollo"

    - name: Creating storage directory
      file:
        path: "{{ arc['data']['volumes_dir'] }}/{{ app_name }}"
        state: directory
        mode: '0755'
        owner: "apollo"
        group: "apollo"

    - name: Copy Stack-File
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ app_dir }}/docker-compose.yml"
        owner: apollo
        group: apollo
        mode: '0644'

    - name: Pull images
      docker_image:
        name: "{{ item.value }}"
        source: pull
      with_dict: "{{ images }}"

    - name: enable registry
      docker_stack:
        state: present
        name: registry
        prune: yes
        with_registry_auth: yes
        compose:
          - "{{ app_dir }}/docker-compose.yml"
  when:
    - arc['addons']['registry']['enabled']|bool

- name: disable registry
  block:
    - name: disable registry
      docker_stack:
        state: absent
        name: registry
  when:
    - not arc['addons']['registry']['enabled']|bool