policies:
    - type: commit
      spec:
        header:
          length: 89
          imperative: true
          case: lower
          invalidLastCharacters: .
        dco: false
        gpg: false
        maximumOfOneCommit: false
        requireCommitBody: false
        conventional:
          types:
            - "type"
          scopes:
            - "scope"
          descriptionLength: 72
  
