stages:
  - version
  - build
  - test
  - release
  - deploy

cache:
  key: "$CI_JOB_NAME"
  
variables:
  DOCKER_TLS_CERTDIR: ""

version:
  stage: version
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  script:
    #- printenv
    - release test-git || true
    - release test-api
    - release next-version --allow-current
    - release next-version --allow-current > .next-version
    - echo "RELEASE_URL=$CI_PROJECT_URL/-/tags/v$(<.next-version)" > build_info
    - echo "RELEASE_DESC=\"$(uname -mo) binary\"" >> build_info
    - echo "RELEASE_SHA=$CI_COMMIT_SHORT_SHA" >> build_info
    - echo "RELEASE_VERSION=$(<.next-version)" >> build_info
  artifacts:
    paths:
    - .next-version
    - build_info
  except:
    - tags
  tags: 
    - build

Build node-exporter:
  stage: build
  image: docker:19.03.5
  variables:
    DOCKER_BUILDKIT: 1 
  services:
    - docker:19.03.5-dind
  script:
    - . build_info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/node-exporter:latest || true
    - cd docker/node-exporter
    - docker build --cache-from $CI_REGISTRY_IMAGE/node-exporter:latest --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $CI_REGISTRY_IMAGE/node-exporter:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE/node-exporter:$CI_COMMIT_SHORT_SHA
  tags: 
    - build

Build prometheus:
  stage: build
  image: docker:19.03.5
  variables:
    DOCKER_BUILDKIT: 1 
  services:
    - docker:19.03.5-dind
  script:
    - . build_info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/prometheus:latest || true
    - cd docker/prometheus
    - docker build --cache-from $CI_REGISTRY_IMAGE/prometheus:latest --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $CI_REGISTRY_IMAGE/prometheus:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE/prometheus:$CI_COMMIT_SHORT_SHA
  tags: 
    - build

Build alertmanager:
  stage: build
  image: docker:19.03.5
  variables:
    DOCKER_BUILDKIT: 1 
  services:
    - docker:19.03.5-dind
  script:
    - . build_info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/alertmanager:latest || true
    - cd docker/alertmanager
    - docker build --cache-from $CI_REGISTRY_IMAGE/alertmanager:latest --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $CI_REGISTRY_IMAGE/alertmanager:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE/alertmanager:$CI_COMMIT_SHORT_SHA
  tags: 
    - build

Build grafana:
  stage: build
  image: docker:19.03.5
  variables:
    DOCKER_BUILDKIT: 1 
  services:
    - docker:19.03.5-dind
  script:
    - . build_info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/grafana:latest || true
    - cd docker/grafana
    - docker build --cache-from $CI_REGISTRY_IMAGE/grafana:latest --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $CI_REGISTRY_IMAGE/grafana:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE/grafana:$CI_COMMIT_SHORT_SHA
  tags: 
    - build

# Build loki:
#   stage: build
#   image: docker:19.03.5
#   variables:
#     DOCKER_BUILDKIT: 1 
#   services:
#     - docker:19.03.5-dind
#   script:
#     - . build_info
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker pull $CI_REGISTRY_IMAGE/loki:latest || true
#     - cd docker/loki
#     - docker build --cache-from $CI_REGISTRY_IMAGE/loki:latest --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $CI_REGISTRY_IMAGE/loki:$CI_COMMIT_SHORT_SHA .
#     - docker push $CI_REGISTRY_IMAGE/loki:$CI_COMMIT_SHORT_SHA
#   tags: 
#     - build

Build zero:
  stage: build
  image: docker:19.03.5
  variables:
    DOCKER_BUILDKIT: 1 
  services:
    - docker:19.03.5-dind
  script:
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY --username=gitlab-ci-token --password-stdin
    - export BASE_IMAGE=$(grep -oE 'FROM .+$' docker/zero/Dockerfile | head -n 1 | cut -d ' ' -f 2)
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker pull $BASE_IMAGE
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest,$BASE_IMAGE --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -f docker/zero/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  tags: 
    - build


# # Lint Ansible files
# test:ansible:
#   stage: test
#   image: $CONTAINER_TEST_IMAGE
#   script:
#     - ansible-lint --version
#     - cd ansible
#     - echo 'Ansible refuses to read from a world-writeable folder, hence' && chmod -v 700 $(pwd)
#     - ansible-lint *.yml
#   allow_failure: true
#   tags: 
#     - infrastructure

Release prometheus:
  stage: release
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  script:
    - . build_info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/prometheus:$CI_COMMIT_SHORT_SHA || true
    - docker tag $CI_REGISTRY_IMAGE/prometheus:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/prometheus:latest
    - docker push $CI_REGISTRY_IMAGE/prometheus:latest
    - docker tag $CI_REGISTRY_IMAGE/prometheus:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/prometheus:v$RELEASE_VERSION
    - docker push $CI_REGISTRY_IMAGE/prometheus:v$RELEASE_VERSION
  only:
    - master
  tags: 
    - build
    - infrastructure

Release alertmanager:
  stage: release
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  script:
    - . build_info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/alertmanager:$CI_COMMIT_SHORT_SHA || true
    - docker tag $CI_REGISTRY_IMAGE/alertmanager:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/alertmanager:latest
    - docker push $CI_REGISTRY_IMAGE/alertmanager:latest
    - docker tag $CI_REGISTRY_IMAGE/alertmanager:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/alertmanager:v$RELEASE_VERSION
    - docker push $CI_REGISTRY_IMAGE/alertmanager:v$RELEASE_VERSION
  only:
    - master
  tags: 
    - build
    - infrastructure

Release grafana:
  stage: release
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  script:
    - . build_info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/grafana:$CI_COMMIT_SHORT_SHA || true
    - docker tag $CI_REGISTRY_IMAGE/grafana:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/grafana:latest
    - docker push $CI_REGISTRY_IMAGE/grafana:latest
    - docker tag $CI_REGISTRY_IMAGE/grafana:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/grafana:v$RELEASE_VERSION
    - docker push $CI_REGISTRY_IMAGE/grafana:v$RELEASE_VERSION
  only:
    - master
  tags: 
    - build
    - infrastructure

Release node-exporter:
  stage: release
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  script:
    - . build_info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/node-exporter:$CI_COMMIT_SHORT_SHA || true
    - docker tag $CI_REGISTRY_IMAGE/node-exporter:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/node-exporter:latest
    - docker push $CI_REGISTRY_IMAGE/node-exporter:latest
    - docker tag $CI_REGISTRY_IMAGE/node-exporter:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/node-exporter:v$RELEASE_VERSION
    - docker push $CI_REGISTRY_IMAGE/node-exporter:v$RELEASE_VERSION
  only:
    - master
  tags: 
    - build

# Release loki:
#   stage: release
#   image: docker:19.03.5
#   services:
#     - docker:19.03.5-dind
#   script:
#     - . build_info
#     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker pull $CI_REGISTRY_IMAGE/loki:$CI_COMMIT_SHORT_SHA || true
#     - docker tag $CI_REGISTRY_IMAGE/loki:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/loki:latest
#     - docker push $CI_REGISTRY_IMAGE/loki:latest
#     - docker tag $CI_REGISTRY_IMAGE/loki:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/loki:v$RELEASE_VERSION
#     - docker push $CI_REGISTRY_IMAGE/loki:v$RELEASE_VERSION
#   only:
#     - master
#   tags: 
#     - build

Release zero:
  stage: release
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  script:
    - . build_info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA || true
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:v$RELEASE_VERSION
    - docker push $CI_REGISTRY_IMAGE:v$RELEASE_VERSION
  only:
    - master
  tags: 
    - build
    - infrastructure

release version:
  stage: release
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  script:
    - rm -f release_info
    - mv build_info release_info
    - . release_info
    - release changelog 
    - release commit-and-tag CHANGELOG.md release_info
  only:
    - master
  tags: 
    - build

# deploy:
#   stage: deploy
#   script:
#     - docker info
#   tags:
#     - deploy

# Deploy
deploy:cio-test:
  stage: deploy
  variables:
    DEPLOYMENT: ${CI_PROJECT_NAME}_test
    APP_ENVIRONMENT: staging
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY --username=$CI_DEPLOY_USER --password-stdin
    - docker stack deploy --with-registry-auth --prune -c docker-compose.yml $DEPLOYMENT
  only:
    - branches
  tags:
    - deploy
