include:
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - fetch-version
  - build
  - test
  - release

fetch-semantic-version:
  image: node:13
  stage: fetch-version
  only:
    refs:
    - master
    - alpha
    - /^(([0-9]+)\.)?([0-9]+)\.x/ # This matches maintenance branches
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ # This matches pre-releases
  script:
    - make install-deps
    - npx semantic-release --generate-notes false --dry-run
  artifacts:
    paths:
    - VERSION.txt

# generate-non-semantic-version:
#   image: node:13
#   stage: fetch-version
#   except:
#     refs:
#     - master
#     - alpha
#     - /^(([0-9]+)\.)?([0-9]+)\.x/ # This matches maintenance branches
#     - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ # This matches pre-releases
#   script:
#     - echo build-$CI_PIPELINE_ID > VERSION.txt
#   artifacts:
#     paths:
#     - VERSION.txt

build-cnab:
  image: 
    name: wearep3r/docker:latest
    entrypoint: [""]
  stage: build
  services:
    - docker:20.10.3-dind
  only:
    refs:
    - master
    - alpha
    # This matches maintenance branches
    - /^(([0-9]+)\.)?([0-9]+)\.x/
    # This matches pre-releases
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ 
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  # before_script:
  #   - apk add bash curl
  #   - curl https://cdn.porter.sh/latest/install-linux.sh | bash
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - /root/.porter/porter build --name apollo --version $(cat VERSION.txt)
    - /root/.porter/porter publish --reference $CI_REGISTRY_IMAGE:$(cat VERSION.txt)

release:
  image: node:13
  stage: release
  only:
    refs:
    - master
    - alpha
    # This matches maintenance branches
    - /^(([0-9]+)\.)?([0-9]+)\.x/
    # This matches pre-releases
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ 
  script:
    - touch CHANGELOG.md
    - make install-deps
    - make release
  artifacts:
    paths:
    - CHANGELOG.md