plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - "@semantic-release/git"
  - "@semantic-release/gitlab"
branches:
  - "master"
  - "main"
  - "next"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "alpha"
    prerelease: true
  - name: "beta"
    prerelease: true
  