version: '3.7'

services:
  database:
    image: mongo:4.1-bionic
    networks:
      - monitoring
    volumes:
      - "mongodb-data:/data/db"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        preferences:
          - spread: node.id
        constraints:
          - node.labels.cio == true
      update_config:
        delay: 60s
        monitor: 30s
        order: start-first
        failure_action: rollback
    logging:
      driver: loki
      options:
          loki-url: "http://loki:3100"
          loki-external-labels: "service=${DEPLOYMENT}"


volumes:
  mongodb-data:
    driver: cio
    driver_opts:
      profile: "SNAPSHOT"


networks:
  monitoring:
    external: true
