# Connect to the first Swarm Manager
# Deploy Controlplane from Stack-File:
# - Copy to Manager from Jinja Template
# - Deploy the Stack
# - Delete the Stack File
- hosts: rolemanager[0]
  remote_user: "{{ deploy_user_name }}"
  become: true
  tasks:
    - name: Create Mbiosphere Overlay networks
      docker_network:
        name: "{{ item }}"
        driver: overlay
      with_items: "{{ mbio_networks }}"
    - name: Copy docker-stack.yml
      template:
        src: docker-stack.yml.j2
        dest: /tmp/docker-stack.yml
        owner: docker
        group: docker
        mode: '0644'
      changed_when: False
    - name: Deploy Controlplane
      docker_stack:
        state: present
        name: controlplane
        compose:
          - /tmp/docker-stack.yml
    - name: Remove docker-stack.yml
      file:
        path: /tmp/docker-stack.yml
        state: absent
      changed_when: False

# Setup Gitlab Runners
- hosts: roleworker
  remote_user: "{{ deploy_user_name }}"
  become: true
  vars_files:
    - group_vars/swarm
  roles:
    - { role: riemers.gitlab-runner }