---
- name: "check version"
  hosts: apollo
  gather_facts: false
  vars:
    apollo_runtime_version: "{{ lookup('env','APOLLO_VERSION') }}"
  tasks:
    - fail: msg="No no no! This is apollo {{ apollo_runtime_version }}, but you wanted to deploy {{ arc['space']['version'] }}"
      when:
        - arc['space']['version'] != ''
        - apollo_runtime_version != arc['space']['version']
  tags:
    - always
    - version

  # Setup facts and populate them for the following plays
- name: "gather facts"
  import_playbook: playbooks/facts.yml
  tags:
    - always
    - facts
  
# If on AWS: fix login user (ubuntu)
- name: "AWS: Enable root access"
  import_playbook: playbooks/aws.yml
  tags:
    - provider_aws
  when: 
    - arc['infrastructure']['enabled']|bool
    - arc['infrastructure']['provider'] == "aws"

# Setup local space configuration (ssh config, docker context, readme)
- name: "setup space"
  import_playbook: playbooks/spaces.yml
  tags:
    - spaces
  when: not in_ci|bool

- name: "deploy"
  import_playbook: playbooks/deploy.yml
  tags:
    - deploy

- name: "recap"
  import_playbook: playbooks/recap.yml
  tags:
    - recap
    - always