add_newline = true
scan_timeout = 10

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
#symbol = "[$APOLLO_SPACE.space]"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[env_var]
variable = "APOLLO_VERSION"
default = "version unknown"
prefix = "apollo "
style = "dimmed bold blue"
disabled = false

[hostname]
disabled = false
