---
- name: Create git user
  user:
    name: "git"
    home: "{{ app_dir }}"
    append: yes
    groups: docker,apollo
    shell: "/bin/bash"

- name: Create git folders
  file:
    path: '{{ item }}'
    state: directory
    owner: git
    group: git
    mode: 0775
    #recurse: yes
  loop:
    - "{{ app_dir }}"
    - "{{ app_dir }}/repos"
    - "{{ app_dir }}/data"
    - "{{ app_dir }}/hooks"
    - "{{ app_dir }}/bin"
    - "{{ app_dir }}/.ssh"

- name: Copy bashrc
  template:
    src: "bashrc.j2"
    dest: "{{ app_dir }}/.bashrc"
    owner: git
    group: git
    mode: 0755

- name: Set up authorized keys for user git
  authorized_key: 
    user: git
    key: "{{ item }}"
    key_options: "no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty,command=\"{{ app_dir }}/bin/sshcommand\""
  with_file:
    - "{{ ansible_ssh_public_key_file }}"
    - "/home/apollo/.ssh/id_rsa.pub"

- name: Copy sshcommand
  template:
    src: templates/sshcommand.j2
    dest: "{{ app_dir }}/bin/sshcommand"
    owner: git
    group: git
    mode: '0775'

- name: Copy shipmate
  template:
    src: templates/shipmate.j2
    dest: "{{ app_dir }}/bin/shipmate"
    owner: git
    group: git
    mode: '0775'

- name: Copy hooks
  template:
    src: templates/post-receive.j2
    dest: "{{ app_dir }}/hooks/post-receive"
    owner: git
    group: git
    mode: '0775'