---
- name: Get existing config.toml
  slurp:
    src: /etc/gitlab-runner/config.toml
  register: runner_config_file
  become: true

- name: Get pre-existing runner configs
  set_fact:
    runner_configs: "{{ (runner_config_file['content'] | b64decode).split('[[runners]]\n') }}"

- name: Create temporary directory
  tempfile:
    state: directory
    suffix: gitlab-runner-config
  register: temp_runner_config_dir
  check_mode: no
  changed_when: false

- name: Write config section for each runner
  include_tasks: config-runner.yml
  loop: "{{ runner_configs }}"
  loop_control:
    index_var: runner_config_index
    loop_var: runner_config

- name: Copy gitlab-runner-wrapper.sh
  copy:
    src: gitlab-runner-wrapper.sh
    dest: "{{ gitlab_runner_temp_dir|default('/tmp', true) }}/gitlab-runner-wrapper.sh"
    mode: 0700
  become: true

- name: Assemble new config.toml
  assemble:
    src: "{{ temp_runner_config_dir.path }}"
    dest: /etc/gitlab-runner/config.toml
    delimiter: '[[runners]]\n'
    backup: yes
    validate: "{{ gitlab_runner_temp_dir|default('/tmp', true) }}/gitlab-runner-wrapper.sh %s"
    mode: 0600
  become: true
