---
# tasks file for zero-app-prometheus
- name: Provision prometheus
  block:
    - name: Creating app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy Stack-File
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ app_dir }}/docker-compose.yml"
        owner: root
        group: root
        mode: '0644'
      register: stack_file

    - name: Create config directories
      file:
        path: "{{ app_dir }}/{{ config_dir.path }}"
        state: directory
        mode: '{{ config_dir.mode }}'
      with_filetree:
        - "files/"
      when: config_dir.state == 'directory'
      loop_control:
        label: "{{ config_dir.path }}"
        loop_var: config_dir

    - name: Copy config files
      copy:
        src: "{{ config_file.src }}"
        dest: "{{ app_dir }}/{{ config_file.path }}"
        mode: "{{ config_file.mode }}"
      with_filetree:
        - "files/"
      when: config_file.state == 'file'
      loop_control:
        label: "{{ config_file.path }}"
        loop_var: config_file

    - name: Setup federation
      block:
        - name: Access federated Spaces
          git:
            repo: "{{ space }}"
            dest: "/tmp/prometheus-federation-space-{{ space_index }}"
          with_items:
            - "{{ prometheus_federation_spaces }}"
          register: prometheus_federation_directories
          loop_control:
            loop_var: space
            index_var: space_index

        - name: Debug federated Spaces
          debug:
            msg: "{{ prometheus_federation_directories }}"
      when: prometheus_federation_enabled|bool

    - name: Copy Prometheus config
      template:
        src: templates/prometheus.yml.j2
        dest: "{{ app_dir }}/prometheus.yml"
        owner: root
        group: root
        mode: '0644'

    - name: Copy Blackbox-Exporter config
      template:
        src: templates/blackbox.yml.j2
        dest: "{{ app_dir }}/blackbox.yml"
        owner: root
        group: root
        mode: '0644'

    - name: Pull images
      docker_image:
        name: "{{ item.value }}"
        source: pull
      with_dict: "{{ images }}"

    # https://github.com/prometheus/prometheus/issues/5976
    - name: Correct volume permissions
      file:
        path: /var/lib/docker/volumes/prometheus_prometheus/
        state: directory
        recurse: yes
        owner: "65534"
        group: "65534"
      when: apollo_data == "generic"

    # TODO: find volume node + id via  cio volume inspect prometheus_prometheus-data
    # - name: Correct volume permissions
    #   file:
    #     path: /cio/volumes/prometheus_prometheus/
    #     state: directory
    #     recurse: yes
    #     owner: "65534"
    #     group: "65534"
    #   when: apollo_data == "storidge"

    - name: Provision prometheus
      docker_stack:
        state: present
        name: prometheus
        prune: yes
        with_registry_auth: yes
        compose:
          - "{{ app_dir }}/docker-compose.yml"
      register: prometheus_provision

    - name: "Wait for http://{{ app_domain }} to become ready"
      uri:
        url: "http://{{ app_domain }}"
        method: GET
        status_code: 200
        validate_certs: no
        user: "{{admin_user}}"
        password: "{{admin_password}}"
      register: _result
      until: _result.status == 200
      retries: 30
      delay: 10