all:
  hosts:
    master-0:
      ansible_host: 78.47.245.165
    node-0:
      ansible_host: 88.99.83.196
    node-1:
      ansible_host: 88.99.82.102
  children:
    master:
      hosts:
        master-0:
    node:
      hosts:
        node-0:        
        node-1:
    k3s_cluster:
      children:
        master:
        node: