---
# tasks file for zero-app-gitlab-runner
- name: Provision gitlab-runner
  block:
    - name: Copy Stack-File
      template:
        src: templates/docker-compose.yml.j2
        dest: /tmp/zero-app-gitlab-runner.yml
        owner: root
        group: root
        mode: '0644'

    - name: Provision gitlab-runner
      docker_stack:
        state: present
        name: gitlab-runner
        prune: yes
        with_registry_auth: yes
        compose:
          - /tmp/zero-app-gitlab-runner.yml
      register: gitlab_runner_provision  