---
- name: restart firewall
  service:
    name: iptables
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: True

- name: restart networking
  service:
    name: networking
    state: restarted
