---
- name: Provision cadvisor 
  block:
    - name: Download cadvisor binary
      become: false
      get_url:
        url: "https://github.com/google/cadvisor/releases/download/v{{ cadvisor_version }}/cadvisor"
        dest: "{{ apollo_downloads_dir }}/cadvisor-v{{ cadvisor_version }}"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: Propagate cadvisor binaries
      copy:
        src: "{{ apollo_downloads_dir }}/cadvisor-v{{ cadvisor_version }}"
        dest: "{{ apollo_binary_dir }}/cadvisor"
        mode: 0755
        owner: apollo
        group: apollo
        remote_src: True
      notify: restart cadvisor
      when: not ansible_check_mode

    - name: Copy the cadvisor systemd service file
      template:
        src: templates/cadvisor.service.j2
        dest: /etc/systemd/system/cadvisor.service
        owner: root
        group: root
        mode: 0644
      notify: restart cadvisor

    - name: Make sure service is started
      service:
        name: cadvisor
        state: started
        enabled: true