---
# handlers file for locale
- name: localectl set-locale
  command: localectl set-locale LANG={{ locale_lang }}
  when:
    - ansible_virtualization_type != "docker"
    - ansible_distribution != "Ubuntu"
    - ansible_distribution  != "Debian"
