auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 1

# schema_config:
#   configs:
#   - from: 2018-04-15
#     store: boltdb
#     object_store: filesystem
#     schema: v9
#     index:
#       prefix: index_
#       period: 168h

schema_config:
  configs:
  - from: 2018-04-15
    store: aws
    object_store: s3
    schema: v10
    index:
      prefix: index_
      period: 24h
      tags:
        app: loki
        env: development

storage_config:
  aws:
    s3: s3://admin:hXltRR7ke4sfBcyOYf3E3@minio:9000/loki-chunks
    s3forcepathstyle: true
    dynamodbconfig:
      dynamodb: dynamodb://dynamodb:8000

# storage_config:
#   boltdb:
#     directory: /tmp/loki/index

#   filesystem:
#     directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 0