---
# vars file for locale
_locale_requirements:
  default: []
  Archlinux:
    - bash
  CentOS: []
  Debian:
    - locales-all
  Fedora:
    - langpacks-en
  Ubuntu:
    - locales-all

locale_requirements: "{{ _locale_requirements[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_locale_requirements[ansible_distribution] | default(_locale_requirements['default'])) }}"

_locale_configuration_file:
  default: /etc/locale.conf
  Debian: /etc/default/locale
  Ubuntu: /etc/default/locale

locale_configuration_file: "{{ _locale_configuration_file[ansible_distribution] | default(_locale_configuration_file['default']) }}"
