---
# tasks file for zero-app-cadvisor
# - name: Provision cadvisor
#   block:
#     - name: Copy Stack-File
#       template:
#         src: templates/docker-compose.yml.j2
#         dest: /tmp/zero-app-cadvisor.yml
#         owner: root
#         group: root
#         mode: '0644'

#     - name: Provision cadvisor
#       docker_stack:
#         state: present
#         name: cadvisor
#         prune: yes
#         with_registry_auth: yes
#         compose:
#           - /tmp/zero-app-cadvisor.yml
#       register: cadvisor_provision  

#   rescue:
#     - name: Teardown cadvisor
#       docker_stack:
#           absent_retries: 5
#           absent_retries_interval: 10
#           state: absent
#           name: cadvisor
#       register: cadvisor_cadvisor

#     - name: Remove Stack File
#       file:
#         path: /tmp/zero-app-cadvisor.yml
#         state: absent

- name: Provision cadvisor 
  block:
    - name: Teardown cadvisor stack
      docker_stack:
        absent_retries: 5
        absent_retries_interval: 10
        state: absent
        name: cadvisor
      when: ansible_hostname == "manager-0"

    - name: Download cadvisor binary
      become: false
      get_url:
        url: "https://github.com/google/cadvisor/releases/download/v{{ cadvisor_version }}/cadvisor"
        dest: "/tmp/cadvisor-v{{ cadvisor_version }}"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: Propagate cadvisor binaries
      copy:
        src: "/tmp/cadvisor-v{{ cadvisor_version }}"
        dest: "{{ _cadvisor_binary_install_dir }}/cadvisor"
        mode: 0755
        owner: root
        group: root
        remote_src: True
      notify: restart cadvisor
      when: not ansible_check_mode

    - name: Copy the cadvisor systemd service file
      template:
        src: templates/cadvisor.service.j2
        dest: /etc/systemd/system/cadvisor.service
        owner: root
        group: root
        mode: 0644
      notify: restart cadvisor

    - name: Make sure service is started
      service:
        name: cadvisor
        state: started
        enabled: true