---
  - name: enable healthcheck
    block:
      - name: Creating app directory
        file:
          path: "{{ app_dir }}"
          state: directory
          mode: '0755'
          owner: "apollo"
          group: "apollo"

      - name: Creating storage directory
        file:
          path: "{{ arc['data']['volumes_dir'] }}/{{ app_name }}"
          state: directory
          mode: '0755'
          owner: "apollo"
          group: "apollo"

      - name: creating healthcheck at provider
        uri:
          url: "{{ arc['providers'][arc['addons']['healthcheck']['provider']]['api']['url'] }}/checks/"
          #headers:
          #  X-Api-Key: "{{ arc['providers'][arc['addons']['healthcheck']['provider']]['auth']['token'] }}"
          method: POST
          body:
            api_key: "{{ arc['providers'][arc['addons']['healthcheck']['provider']]['auth']['token'] }}"
            name: "{{ arc['space']['space_domain'] }}"
            tags: "{{ arc['space']['name'] }} apollo"
            timeout: 3600 
            grace: 300
            schedule: "0/10 * * * *"
            desc: "apollo healtcheck for {{ arc['space']['name'] }}"
            unique:
              - name
          status_code: 
            - 201
            - 200
          body_format: json
        register: healthcheck_api
      
      - name: debug healthcheck ping url
        debug:
          msg: "healthcheck ping url: {{ healthcheck_api }}"
          verbosity: 1

      - name: expose ping_url
        set_fact:
          ping_url: "{{ healthcheck_api.json.ping_url }}"
  
      # - name: Copy Stack-File
      #   template:
      #     src: templates/docker-compose.yml.j2
      #     dest: "{{ app_dir }}/docker-compose.yml"
      #     mode: '0644'
      #     owner: apollo
      #     group: apollo
      #   register: stack_file
  
      # - name: Pull images
      #   docker_image:
      #     name: "{{ item.value }}"
      #     source: pull
      #   with_dict: "{{ images }}"
      
      # - name: enable healthcheck
      #   docker_stack:
      #     state: present
      #     name: healthcheck
      #     prune: yes
      #     with_registry_auth: yes
      #     compose:
      #       - "{{ app_dir }}/docker-compose.yml"
      - name: Copy the healthcheck systemd service file
        template:
          src: templates/healthcheck.service.j2
          dest: /etc/systemd/system/healthcheck.service
          owner: root
          group: root
          mode: 0644

      - name: Copy the healthcheck systemd timer file
        template:
          src: templates/healthcheck.timer.j2
          dest: /etc/systemd/system/healthcheck.timer
          owner: root
          group: root
          mode: 0644
      
      - name: Enable healthcheck service
        systemd:
          name: "healthcheck"
          enabled: true

      - name: Enable healthcheck timer
        systemd:
          name: "healthcheck.timer"
          state: started
          enabled: true

      - name: restart systemd
        become: true
        systemd:
          daemon_reload: true

      - name: remove legacy healthcheck
        docker_stack:
          state: absent
          name: healthcheck
          prune: yes
    when:
      - arc['addons']['healthcheck']['enabled']|bool
    tags:
      - proxy
  
  - name: disable healthcheck
    block:
      - name: Stop and disable healthcheck
        systemd:
          name: "healthcheck"
          enabled: false
          state: stopped

      - name: Stop and disable healthcheck timer
        systemd:
          name: "healthcheck.timer"
          enabled: false
          state: stopped

    when:
      - not arc['addons']['healthcheck']['enabled']|bool
    tags:
      - proxy