apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
- name: Prometheus
  type: prometheus
  # access: proxy
  url: http://victoria-metrics:8428
  isDefault: true
  version: 1
  editable: false