---
# tasks file for zero-app-cadvisor
- name: Provision garbage-collector
  block:
    - name: Creating app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        owner: "apollo"
        group: "apollo"

    - name: Creating storage directory
      file:
        path: "{{ arc['data']['volumes_dir'] }}/{{ app_name }}"
        state: directory
        mode: '0755'
        owner: "apollo"
        group: "apollo"

    - name: Download docker-gc binary
      become: false
      get_url:
        url: "https://raw.githubusercontent.com/spotify/docker-gc/master/docker-gc"
        dest: "{{ apollo_binary_dir }}/docker-gc"
        mode: '0755'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: Create docker-gc-exclude
      copy:
        dest: "/etc/docker-gc-exclude"
        content: |
          e61267dbe31b
        backup: false
        owner: root
        group: root
        mode: 0640

    - name: "Copy apollo-gc script"
      template:
        src: templates/apollo-gc.j2
        dest: "{{ app_dir }}/apollo-gc"
        owner: root
        group: root
        mode: 0755

    - name: "Copy docker-gc environment file"
      template:
        src: templates/docker-gc.env.j2
        dest: "{{ app_dir }}/docker-gc.env"
        owner: root
        group: root
        mode: 0644
  
    - name: "Copy {{ app_name }} systemd service file"
      template:
        src: templates/garbage-collector.service.j2
        dest: /etc/systemd/system/garbage-collector.service
        owner: root
        group: root
        mode: 0644

    - name: Copy {{ app_name }} systemd timer file
      template:
        src: templates/garbage-collector.timer.j2
        dest: /etc/systemd/system/garbage-collector.timer
        owner: root
        group: root
        mode: 0644

    - name: Enable garbage-collector service
      systemd:
        name: "garbage-collector"
        state: started
        enabled: true

    - name: restart systemd
      become: true
      systemd:
        daemon_reload: true

    - name: Enable garbage-collector timer
      systemd:
        name: "garbage-collector.timer"
        state: started
        enabled: true

    - name: restart systemd
      become: true
      systemd:
        daemon_reload: true

    