version: '3.7'

services:
  av:
    image: mk0x/docker-clamav:alpine
    networks:
      - nextcloud
    restart: unless-stopped
  
  app:
    image: hoellen/nextcloud:18.0
    #image: munchiez/rootless-nextcloud
    networks:
      - nextcloud
      - proxy
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Berlin
      - ADMIN_USER={{ admin_user }}
      - ADMIN_PASSWORD={{ admin_password }}
      - DOMAIN=nextcloud.{{ base_domain }}
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=nextcloud
      - DB_HOST=db
    volumes:
      - data:/data
      - config:/config
      - apps:/apps2
      - themes:/nextcloud/themes
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        preferences:
          - spread: node.id
      update_config:
        delay: 60s
        monitor: 30s
        order: start-first
        failure_action: rollback
      rollback_config:
        delay: 60s
        monitor: 30s
        order: start-first
        failure_action: pause
      labels:    
        - traefik.backend.loadbalancer.stickiness=true
        - traefik.frontend.rule=Host:nextcloud.{{ base_domain }}
        - traefik.enable=true
        - traefik.tags=proxy
        - traefik.port=8888
        - traefik.protocol=http
        - traefik.frontend.entryPoints=http,https
        - traefik.docker.network=proxy
        - traefik.backend=nextcloud
        - traefik.frontend.headers.SSLRedirect=true
        #- traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav
        #- traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/
        #- "traefik.frontend.headers.contentSecurityPolicy=default-src 'self';frame-ancestors 'self';style-src 'self' 'unsafe-inline';script-src 'self' 'unsafe-inline' 'unsafe-eval';img-src 'self' data:;font-src 'self' data:"

  db:
    image: mariadb:10
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - nextcloud
    volumes:
      - db:/var/lib/mysql
  
  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud
    volumes:
      - redis:/data


volumes:
  redis:
  db:
  data:
  config:
  apps:
  themes:
networks:
  nextcloud:
  proxy:
    external: true
  ldap:
    external: true
  mail:
    external: true
  auth:
    external: true
  monitoring:
    external: true