# Setup Gitlab Runners
- hosts: satellite
  remote_user: "{{ deploy_user_name }}"
  become: true
  vars:
    gitlab_runner_package_name: 'gitlab-runner'
    #gitlab_runner_coordinator_url: "https://gitlab.com"
    gitlab_runner_registration_token: "{{ runner_token }}"
    gitlab_runner_concurrent: 4
    gitlab_runner_listen_address: ":9252"
    gitlab_runner_runners:
      - name: "{{ ansible_hostname }}"
        executor: docker
        docker_image: "{{ ci_docker_image }}"
        tags:
          - docker
          - staging
          - infrastructure
          - build
        docker_privileged: true
        docker_volumes:
          - "/cache"
        extra_configs:
          runners.docker:
            memory: 2048mb
            privileged: true
            disable_cache: false
        #    #allowed_images: ["ruby:*", "python:*", "php:*"]
        #  runners.docker.sysctls:
        #    net.ipv4.ip_forward: "1"
  roles:
    - { role: riemers.gitlab-runner }

- hosts: manager
  remote_user: "{{ deploy_user_name }}"
  become: true
  vars:
    gitlab_runner_package_name: 'gitlab-runner'
    #gitlab_runner_coordinator_url: "https://gitlab.com"
    gitlab_runner_registration_token: "{{ runner_token }}"
    gitlab_runner_concurrent: 1
    gitlab_runner_listen_address: ":9252"
    gitlab_runner_runners:
      - name: "{{ ansible_hostname }}"
        executor: docker
        docker_image: "{{ ci_docker_image }"
        tags:
          - docker
          - staging
          - infrastructure
          - deploy
        docker_privileged: true
        docker_volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/cache"
        extra_configs:
          runners.docker:
            memory: 512mb
            privileged: true
            disable_cache: false
            allowed_images: ["{{ ci_docker_image }}:*"]
        limit: 1
  roles:
    - { role: riemers.gitlab-runner }