- hosts: manager[0]
  remote_user: "{{ deploy_user_name }}"
  become: True
  tasks:
    - name: Delete A record for Runners
      cloudflare_dns:
        zone: "{{ base_domain }}"
        record: "runners"
        type: A
        state: absent
        account_email: "{{ cf_api_email }}"
        account_api_token: "{{ cf_api_key }}"
      register: record
      tags:
        - dns

- hosts: satellite
  remote_user: "{{ deploy_user_name }}"
  become: True
  vars:
    gitlab_runner_package_name: 'gitlab-runner'
    #gitlab_runner_coordinator_url: "https://gitlab.com"
    gitlab_runner_registration_token: "{{ runner_token }}"
    gitlab_runner_concurrent: 4
    gitlab_runner_listen_address: ":9252"
    gitlab_runner_runners:
      - name: "{{ ansible_hostname }}-runner"
        env_vars:
          GL_TOKEN="{{ gl_token }}"
        executor: docker
        docker_image: "{{ ci_docker_image }}"
        tags:
          - docker
          - infrastructure
          - build
        docker_privileged: True
        docker_volumes:
          - "/cache"
        extra_configs:
          runners.docker:
            memory: 2048mb
            privileged: True
            disable_cache: False
  roles:
    - { role: riemers.gitlab-runner }
  tags:
    - runner
    - build
  tasks:
    # Here we're overloading the nodes.mbiosphere.com A-Record with the IP of each node.
    # This way we don't need to specify each Swarm Node in the Prometheus Config
    # but can use the same mechanic of discovery that is used by the other exporters.
    # Prometheus simply queries nodes.mbiosphere.com and gets a list of IPs returned
    # which it then scrapes.
    #
    # EXAMPLE
    #
    # $ dig nodes.mbiosphere.com
    #
    # ;; ANSWER SECTION:
    # nodes.mbiosphere.com.	299	IN	A	157.230.122.88
    # nodes.mbiosphere.com.	299	IN	A	157.230.101.99
    # nodes.mbiosphere.com.	299	IN	A	68.183.219.80
    # nodes.mbiosphere.com.	299	IN	A	157.230.101.24
    # nodes.mbiosphere.com.	299	IN	A	157.230.123.216
    # nodes.mbiosphere.com.	299	IN	A	157.230.99.2
    # nodes.mbiosphere.com.	299	IN	A	157.230.109.225
    - name: Create A record for Runners (Prometheus)
      cloudflare_dns:
        zone: "{{ base_domain }}"
        record: "runners"
        type: A
        value: "{{ ansible_default_ipv4.address }}"
        account_email: "{{ cf_api_email }}"
        account_api_token: "{{ cf_api_key }}"
      register: record
      tags:
        - dns

- hosts: manager
  remote_user: "{{ deploy_user_name }}"
  become: True
  vars:
    gitlab_runner_package_name: 'gitlab-runner'
    #gitlab_runner_coordinator_url: "https://gitlab.com"
    gitlab_runner_registration_token: "{{ runner_token }}"
    gitlab_runner_concurrent: 1
    gitlab_runner_listen_address: ":9252"
    gitlab_runner_runners:
      - name: "{{ ansible_hostname }}-runner"
        env_vars:
          GL_TOKEN="{{ gl_token }}"
        executor: docker
        docker_image: "{{ ci_docker_image }}"
        tags:
          - deploy
        docker_privileged: True
        docker_volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/cache"
        extra_configs:
          runners.docker:
            memory: 512mb
            privileged: True
            disable_cache: False
            allowed_images: ["docker:*"]
  roles:
    - { role: riemers.gitlab-runner }
  tags:
    - runner
    - deploy
  tasks:
    - name: Create A record for Runners (Prometheus)
      cloudflare_dns:
        zone: "{{ base_domain }}"
        record: "runners"
        type: A
        value: "{{ ansible_default_ipv4.address }}"
        account_email: "{{ cf_api_email }}"
        account_api_token: "{{ cf_api_key }}"
      register: record
      tags:
        - dns
