- hosts: swarm
  become: True
  remote_user: "{{ deploy_user_name }}"
  gather_facts: False
  tasks:
    - name: Disable Storidge service
      service:
        name: cio
        enabled: False

    - name: Remove Cluster Config
      file:
        path: /etc/storidge/config/default.cfg
        state: absent

    - name: Reboot Node
      reboot:
        reboot_timeout: 180

    - name: Wait for system to become reachable again
      wait_for_connection:
          delay: 60
          timeout: 180
