# Create Staging/Production Managers and Workers
# Check if the provisioning succeeded
# Wait 100s for hosts to come up if they've been recently created/changed
- name: Create Swarm Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  user: root
  tasks:
    - name: Debug
      debug:
        msg: Item {{ item.location }}
      #loop: "{{ nodes.manager|dict2items }}"
      with_items: "{{ nodes.manager }}"
    
    - name: Remove Managers
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ item.name }}"
        server_type: cx41
        image: ubuntu-16.04
        location: "{{ item.location }}"
        ssh_keys:
          - MBio DevOps
        state: absent
        labels:
          swarm: ""
          manager: ""
          mbiosphere: ""
        backups: no
      with_items: "{{ nodes.manager }}"
    - name: Wait for Nodes to be down
      pause:
        prompt: "Waiting for nodes be fully shut down"
        seconds: 30
    - name: Remove 3 Volumes for each Node
      hcloud_volume:
        api_token: "{{ hcloud_token }}"
        name: "{{ item[0].name+'-'+item[1] }}"
        server: ""
        size: 50
        state: absent
        automount: no
      with_nested:
        - "{{ nodes.manager }}"
        - ["block-1", "block-2", "block-3"]
    - name: Remove Workers
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ item.name }}"
        server_type: cx41
        image: ubuntu-16.04
        location: "{{ item.location }}"
        ssh_keys:
          - MBio DevOps
        state: absent
        labels:
          swarm: ""
          worker: ""
          mbiosphere: ""
        backups: no
      with_items: "{{ nodes.worker }}"
    - name: Wait for Nodes to be down
      pause:
        prompt: "Waiting for nodes be fully shut down"
        seconds: 30
    - name: Remove 3 Volumes for each Node
      hcloud_volume:
        api_token: "{{ hcloud_token }}"
        name: "{{ item[0].name+'-'+item[1] }}"
        server: "{{ item[0].name }}"
        size: 50
        state: absent
        automount: no
      with_nested:
        - "{{ nodes.worker }}"
        - ["block-1", "block-2", "block-3"]
    - name: Remove Swarm Subnet
      hcloud_subnetwork:
        api_token: "{{ hcloud_token }}"
        network: swarm
        ip_range: 10.0.0.0/16
        network_zone: eu-central
        type: server
        state: absent
    - name: Remove Swarm network
      hcloud_network:
        api_token: "{{ hcloud_token }}"
        name: swarm
        ip_range: 10.0.0.0/8
        state: absent
        labels:
          swarm: ""
          mbiosphere: ""

    # - name: Remove Runners
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: "{{ item.name }}"
    #     server_type: cx11
    #     image: ubuntu-18.04
    #     location: "{{ item.location }}"
    #     ssh_keys:
    #       - MBio DevOps
    #     state: absent
    #     labels:
    #       runner: ""
    #       mbiosphere: ""
    #     backups: no
    #   with_items: "{{ nodes.runner }}"
    - name: Refresh inventory to ensure new instances exist in inventory
      meta: refresh_inventory
