---
- name: restart vmagent
  become: true
  systemd:
    daemon_reload: true
    name: vmagent
    state: restarted

- name: restart victoria
  become: true
  systemd:
    daemon_reload: true
    name: victoria
    state: restarted

- name: restart blackbox_exporter
  become: true
  systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: restarted

- name: restart process_exporter
  become: true
  systemd:
    daemon_reload: true
    name: process_exporter
    state: restarted