apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
- name: Victoria Metrics
  type: prometheus
  access: proxy
  url: http://victoria-metrics:8428
  isDefault: true
  version: 1
  editable: false