debug = false
logLevel = "INFO"
insecureSkipVerify = true

[accessLog]

[entryPoints]
	[entryPoints.http]
	address  = ":80"
	[entryPoints.https]
	address = ":443"
	  [entryPoints.https.tls]

[api]
  entrypoint="traefik"
  dashboard = true

[retry]
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "mbiosphere.com"
  watch = true
  exposedByDefault = false

[acme]
  email = "cloud@micro-biolytics.com"
  storage = "/etc/traefik/acme.json"
  entryPoint = "https"
  onHostRule = true
  [acme.dnsChallenge]
    provider = "cloudflare"
    deleayBeforeCheck = 0
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
  [[acme.domains]]
    main = "*.mbiosphere.com"
    sans = ["mbiosphere.com"]

  [[acme.domains]]
    main = "*.staging.mbiosphere.com"
    sans = ["staging.mbiosphere.com"]