version: '3.7'

services:
  dashmachine:
    image: rmountjoy/dashmachine:latest
    networks:
      - dashmachine
    volumes:
      - dashmachine-data:/dashmachine/dashmachine/user_data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        preferences:
          - spread: node.id
      update_config:
        delay: 60s
        monitor: 30s
        order: start-first
        failure_action: rollback
      rollback_config:
        delay: 60s
        monitor: 30s
        order: start-first
        failure_action: pause
      labels:    
        - traefik.backend.loadbalancer.stickiness=true
        - traefik.frontend.rule=Host:dashboard.{{ base_domain }}
        - traefik.enable=true
        - traefik.tags=proxy
        - traefik.port=5000
        - traefik.protocol=http
        - traefik.frontend.entryPoints=http,https
        - traefik.docker.network=proxy
        - traefik.backend=dashmachine
        - traefik.frontend.headers.SSLRedirect=true
        
volumes:
  dashmachine-data:
networks:
  dashmachine:
  proxy:
    external: true