---

# - name: setup kubernetes 
#   win_chocolatey:
#     state: present  
#     name: "{{ item }}"
#     force: yes
#     ignore_checksums: yes
#     version:  1.14.0-rc1
#   with_items: 
#     - kubernetes-node 
  
- name: Create directory 
  win_file:
    path: C:\k
    state: directory

- name: Copy PrepareNode script
  win_copy:
    src: files/PrepareNode.ps1
    dest: C:\k\PrepareNode.ps1

- name: Run PrepareNode script
  win_shell: C:\k\PrepareNode.ps1 -KubernetesVersion v1.18.0 >> c:\k\PrepareNode_log.txt

- name: Reboot Server
  win_reboot:
    reboot_timeout: 3600
    post_reboot_delay: 60
  ignore_errors: yes

- name: Join node to Kubernetes master
  win_shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  tags: ['skip_ansible_lint']
  when: inventory_hostname != groups["manager"][0]