# This Playbook does a few checks against the local Git Repository
# to ensure you're not running this Infrastructure Blueprint against
# a productive cluster from a different Branch than MASTER or with outdated Code (i.e. MASTER not up-to-date)
- name: Check Git Status
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get current Git Branch
      command: git rev-parse --abbrev-ref HEAD
      register: git_branch
      changed_when: 'git_branch.stdout != "master"'
    - name: Abort if current Git Branch not MASTER
      fail: msg="You're on Branch {{ git_branch.stdout }}. Please switch to MASTER to continue."
      when: 'git_branch.stdout != "master"'
    - name: Get local Git Status
      command: git rev-parse @
      register: git_local_status
      changed_when: False
    - name: Get remote Git Status
      command: git rev-parse '@{u}'
      register: git_remote_status
      changed_when: False
    - name: Check for Updates
      fail: msg="Your Branch (local MASTER@{{ git_local_status.stdout }}) is not up-to-date (remote MASTER@{{ git_remote_status.stdout }}). Please run 'git pull'."
      when: 'git_local_status.stdout != git_remote_status.stdout'