# @meta author: Fabian Peter
# @meta description: MBIO Cloud
# @meta email: fabian@peter.saarland
# @action provision # this action describes the installation  
---
# Check git Status
- import_playbook: playbooks/git-status.yml
  # See group_vars/all
  when: check_git
# Create/Update Nodes on HETZNER Cloud
- import_playbook: playbooks/provision-hetzner.yml
# Configure each Node: install software, set config
- import_playbook: playbooks/provision-node.yml
# Security hardening
- import_playbook: playbooks/harden-node.yml
# Bootstrap/Update GitLab Runners
- import_playbook: playbooks/provision-runner.yml
# Bootstrap/Update the Swarm
- import_playbook: playbooks/provision-swarm.yml
# Bootstrap/Update Storidge
#- import_playbook: provision-storidge.yml