# @meta author: Fabian Peter
# @meta description: MBIO Cloud
# @meta email: fabian@peter.saarland
# @action provision # this action describes the installation  
---
# Check git Status
- import_playbook: playbooks/git-status.yml
  # See group_vars/all
  when: check_git
- import_playbook: playbooks/provision-infrastructure.yml
- import_playbook: playbooks/provision-node.yml
- import_playbook: playbooks/provision-swarm.yml
- import_playbook: playbooks/provision-storidge.yml
- import_playbook: playbooks/provision-runner.yml
- import_playbook: playbooks/provision-services.yml