- name: Provisioning Infrastructure with Terraform
  terraform:
    project_path: ../terraform
    state: present
    variables:
      digitalocean_auth_token: "{{digitalocean_auth_token}}"
      digitalocean_ssh_key_id: "{{digitalocean_ssh_key_id}}"
      manager_count: "{{manager_count}}"
      worker_count: "{{worker_count}}"
      satellite_count: "{{satellite_count}}"
      volume_count: "{{volume_count}}"
  register: terraform
  async: 1000
  poll: 0
- name: Waiting for Infrastructure to be Deployed
  async_status:
    jid: "{{ terraform.ansible_job_id }}"
  register: terraform_result
  until: terraform_result.finished
  retries: 30
  delay: 10
- name: Debug Terraform
  debug:
    var: terraform_result 
    verbosity: 1
- name: Refreshing Inventory
  meta: refresh_inventory
- name: Clearing gathered facts
  meta: clear_facts