global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'prometheus'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      # This A-Record is managed by Docker Swarm
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      # This A-Record is managed by Docker Swarm
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      # This A-Record is managed by Docker Swarm
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'cio-exporter'
    dns_sd_configs:
    - names:
      # This A-Record is managed by Docker Swarm
      - 'tasks.cio-exporter'
      type: 'A'
      port: 16995

  - job_name: 'traefik'
    dns_sd_configs:
    - names:
      # This A-Record is managed by Docker Swarm
      - 'tasks.traefik'
      type: 'A'
      port: 8080

  # - job_name: 'giltlab-runner'
  #   dns_sd_configs:
  #   - names:
  #     # This A-Record is managed by Ansible in `playbooks/provision-node.yml`
  #     - 'runners.zero.local'
  #     type: 'A'
  #     port: 9252