---
# handlers file for zero-core
- name: restart firewall
  service:
    name: iptables
    state: restarted
- name: reload systemd
  systemd:
    daemon_reload: True

- name: restart resolvconf
  service:
    name: resolvconf
    state: restarted