- name: "@apollo-cleanup"
  become: True
  gather_facts: False
  hosts: manager[0]
  tasks:
    - name: "Gather Package facts"
      package_facts:
        manager: "auto"

    - name: "removing legacy docker stacks"
      docker_stack:
        absent_retries: 5
        absent_retries_interval: 10
        state: absent
        name: "{{ item }}"
      when: 
        - "'docker-ce' in ansible_facts.packages"
      with_items:
        - cadvisor
        - alertmanager
        - prometheus
        - node-exporter
        - promtail
        - grafana
        - garbage-collector
        - loki

- name: "@apollo-traefik"
  become: True
  hosts: manager[0]
  roles:
    - apollo-app-traefik
  tags:
    - traefik

- name: "@apollo-logs"
  become: True
  hosts: 
    - manager
    - worker
  roles:
    - apollo-app-loki
    - apollo-app-promtail
  tags:
    - logs

- name: "@apollo-metrics"
  become: True
  hosts: 
    - manager
    - worker
  roles:
    - apollo-app-node-exporter
    - apollo-app-process-exporter
    - apollo-app-cadvisor
  tags:
    - metrics

- name: "@apollo-metrics"
  become: True
  hosts: manager[0]
  roles:
    - apollo-app-node-exporter
    - apollo-app-process-exporter
    - apollo-app-cadvisor
    - apollo-app-victoria
  tags:
    - metrics

- name: "@apollo-alerts"
  become: True
  hosts: manager[0]
  roles:
    - apollo-app-alerts
  tags:
    - alerts

- name: "@apollo-analytics"
  become: True
  hosts: manager[0]
  roles:
    - apollo-app-grafana
  tags:
    - analytics

# - name: "@apollo-garbage-collector"
#   become: True
#   hosts: manager[0]
#   roles:
#     - apollo-app-garbage-collector

# - name: "@apollo-backups"
#   become: True
#   hosts: manager[0]
#   roles:
#     - zero-app-lake0