- name: "@apollo-gitlab-runner deploy"
  hosts: manager
  become: True
  pre_tasks:
    - name: List Runners
      command: "gitlab-runner list"
      register: registered_runners
      ignore_errors: True

    - name: Unregister Runners
      command: "gitlab-runner unregister --name {{ ansible_hostname }}-deploy"
      when: 'registered_runners is defined and "{{ ansible_hostname }}-deploy" in registered_runners.stderr'
      ignore_errors: True
  vars:
    gitlab_runner_concurrent: 1
    gitlab_runner_runners:
      - name: "{{ ansible_hostname }}-deploy"
        env_vars:
          - "DOCKER_DRIVER=overlay2"
          - "DOCKER_BUILDKIT=1"
          - "DOCKER_HOST=unix:///var/run/docker.sock"
          - "APOLLO_INGRESS_IP={{ apollo_ingress_ip }}"
        executor: docker
        docker_image: "{{ ci_docker_image }}"
        tags:
          - deploy
          - ship
          - "{{ apollo_space }}"
        run_untagged: false
        docker_privileged: True
        docker_volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        extra_configs:
          runners.custom_build_dir: 
            enabled: True
          runners.docker:
            privileged: True
            disable_cache: False
            #allowed_images: ["*/*:*"]
  roles:
    - { role: riemers.gitlab-runner }
  tags:
    - runner
    - deploy