- name: "@apollo-facts"
  hosts: all
  gather_facts: True
  become: true
  tasks:
    - name: Setup facts
      setup:
        filter: "*"

    - name: Check for required config
      fail: msg="{{ item }} is not defined"
      when: not item
      with_items:
        - "{{ apollo_required_vars }}"

    - name: Set Node Facts
      set_fact:
        apollo_manager: "{{  hostvars[groups['manager'][0]]['ansible_default_ipv4']['address'] }}"
        cluster_ip: "{{  hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        apollo_public_ip: "{{  hostvars[groups['manager'][0]]['ansible_default_ipv4']['address'] }}"
        apollo_public_interface: "{{  hostvars[inventory_hostname]['ansible_default_ipv4']['interface'] }}"
        apollo_private_interface: "{{  hostvars[inventory_hostname]['ansible_default_ipv4']['interface'] }}"

    - name: Update Node Facts (Wireguard)
      set_fact:  
        apollo_manager: "{{ hostvars[groups['manager'][0]]['apollo_cluster_ip'] }}"
        cluster_ip: "{{  hostvars[inventory_hostname]['apollo_cluster_ip'] }}"
      when: apollo_wireguard_enabled|bool

    