- name: "@apollo-spaces"
  hosts: localhost
  become: True
  strategy: linear
  gather_facts: False
  tasks:
    - name: space README
      block:
        - name: Create README.md config for space
          template:
            src: "README.md.j2"
            dest: "{{ apollo_space_dir }}/README.md"
            owner: root
            group: root
            mode: 0755

    - name: space QR code
      block:
        - name: Create QR code for Portainer
          command: "qrencode -o {{ apollo_space_dir }}/logo.png https://portainer.{{ space_domain }}"
            args:
              creates: "{{ apollo_space_dir }}/logo.png"

    - name: SSH Configs
      block:
        - name: Create SSH config for space
          template:
            src: "ssh-config.j2"
            dest: "{{ apollo_space_dir }}/.ssh/config"
            owner: root
            group: root
            mode: 0755

        - name: Include Space in ssh config
          lineinfile: 
            dest: /root/.ssh/config
            #regexp=".*Include$" 
            line: "Include {{ apollo_space_dir | replace('/root', '~') }}/.ssh/config" 
            state: present

    - name: Probe for Docker directory
      stat:
        path: /root/.docker
      register: docker_directory

    - name: Docker Contexts
      block:
        - name: Creating Docker contexts directory
          file:
            path: "/root/.docker/contexts"
            state: directory
            mode: '0755'

        - name: Create Docker context for space
          template:
            src: "docker-context.j2"
            dest: "/root/.docker/contexts/{{ space_domain }}"
            owner: root
            group: root
            mode: 0755

        - name: Include Space in ssh config
          lineinfile: 
            dest: /root/.ssh/config
            #regexp=".*Include$" 
            line: "Include {{ apollo_space_dir | replace('/root', '~') }}/.ssh/config" 
            state: present
      when: docker_directory.stat.exists
