- name: "@apollo-gitlab-runner build"
  hosts: 
    - manager
    - worker
  become: True
  pre_tasks:
    - name: List Runners
      command: "gitlab-runner list"
      register: registered_runners
      ignore_errors: True
    
    - name: Unregister Runners
      command: "gitlab-runner unregister --name {{ ansible_hostname }}-build"
      when: 'registered_runners is defined and "{{ ansible_hostname }}-build" in registered_runners.stderr'
      ignore_errors: True

    - name: Creating storage directory
      file:
        path: "{{ apollo_data_volumes_dir }}/gitlab-runner-build/cache"
        state: directory
        mode: '0755'
        owner: "root"
        group: "root"
  vars:
    gitlab_runner_runners:
      - name: "{{ ansible_hostname }}-build"
        env_vars:
          - "DOCKER_DRIVER=overlay2"
          - "DOCKER_BUILDKIT=1"
          - "APOLLO_INGRESS_IP={{ apollo_ingress_ip }}"
        token: "{{ arc['gitlab']['runner']['token'] }}"
        executor: docker
        docker_image: "{{ ci_docker_image }}"
        tags:
          - "{{ arc['space']['name'] }}"
          - build
        run_untagged: True
        docker_privileged: True
        docker_volumes:
          - "{{ apollo_data_volumes_dir }}/gitlab-runner-build/cache:/cache"
          #- "/var/run/docker.sock:/var/run/docker.sock"
        extra_configs:
          runners.custom_build_dir: 
            enabled: True
          runners.docker:
            privileged: True
            disable_cache: False
  roles:
    - { role: riemers.gitlab-runner }
  tags:
    - runner
    - build