- import_playbook: apollo-facts.yml

- name: "@apollo-proxy"
  become: True
  hosts: manager[0]
  gather_facts: True
  roles:
    - apollo-app-traefik

- name: "@apollo-monitoring"
  become: True
  hosts: all
  gather_facts: True
  roles:
    - apollo-app-node-exporter
    - apollo-app-cadvisor

- name: "@apollo-logs"
  become: True
  hosts: all
  gather_facts: True
  roles:
    - apollo-app-loki
    - apollo-app-promtail

- name: "@apollo-metrics"
  become: True
  hosts: manager[0]
  gather_facts: True
  roles:
    - apollo-app-victoria

- name: "@apollo-alerts"
  become: True
  hosts: manager[0]
  gather_facts: True
  roles:
    - zero-app-alertmanager

- name: "@apollo-status"
  become: True
  hosts: manager[0]
  gather_facts: True
  roles:
    - apollo-app-grafana

- name: "@apollo-garbage-collector"
  become: True
  hosts: manager[0]
  gather_facts: True
  roles:
    - apollo-app-garbage-collector

- name: "@apollo-backups"
  become: True
  hosts: manager[0]
  gather_facts: True
  roles:
    - zero-app-lake0