- name: "@apollo-security"
  hosts: 
    - manager
    - worker
  gather_facts: true
  become: true
  roles:
    - dev-sec.os-hardening
  vars:
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
      net.ipv4.tcp_window_scaling: 0
      net.ipv6.conf.all.disable_ipv6: 0