- name: "@apollo-federation"
  hosts: localhost
  become: True
  tasks:
    - name: Gather Space information
      block:
        - name: Make sure federation directory exists
          file:
            path: "{{ apollo_federation_dir }}"
            state: directory
            mode: '0755'
        
        - name: Make sure space federation directory exists
          file:
            path: "{{ apollo_federation_dir }}/{{ arc['space']['name'] }}"
            state: directory
            mode: '0755'

        - name: Clone Spaces
          git:
            repo: "{{ apollo_federation_space }}"
            dest: "{{ apollo_federation_dir }}/{{ arc['space']['name'] }}/federation-space-{{ apollo_federation_space_index }}"
            key_file: "{{ ansible_ssh_private_key_file }}"
          register: apollo_federation_spaces_directories
          with_items:
            - "{{ apollo_federation_spaces }}"
          loop_control:
            loop_var: apollo_federation_space
            index_var: apollo_federation_space_index
        
        - name: Debug Spaces
          debug:
            msg: "{{ apollo_federation_spaces_directories.results }}"

        - name: Load Federation Space variables
          add_host:
            msg: 
              - "{{ lookup('ini', 'APOLLO_BASE_DOMAIN file='+item.invocation.module_args.dest+'/apollo.env') }}"
              - "{{ item }}"
          with_items:
            - "{{ apollo_federation_spaces_directories.results }}"
          #when: item.state == 'file'
          #loop: "{{ lookup('fileglob', 'plugins/*', wantlist=True) }}"