- name: "@apollo-monitoring"
  become: True
  hosts: all
  gather_facts: True
  roles:
    - apollo-app-node-exporter

- name: "@apollo-alerts"
  become: True
  hosts: manager[0]
  gather_facts: True
  roles:
    - zero-app-alertmanager

- name: "@apollo-backups"
  become: True
  hosts: manager[0]
  gather_facts: True
  roles:
    - zero-app-lake0

- name: "@apollo-backplane"
  hosts: manager[0]
  become: True
  gather_facts: True
  roles:
    - apollo-backplane