- hosts: all
  become: True
  remote_user: "ubuntu" # AWS EC2 VMs by default only allow login to user 'ubuntu', by preventing root login through prefixing the ssh key in /root/.ssh/authorized_keys
  gather_facts: False
  tasks:
    - name: Fixing AWS root SSH access
      replace:
        path: /root/.ssh/authorized_keys
        regexp: "^.*(?=(ssh-rsa))"
        replace: ""
      when: aws_enabled|bool