- hosts: localhost
  tasks:
    - name: Provisioning Infrastructure with Terraform
      terraform:
        project_path: ../terraform
        state: present
        variables:
          do_token: "{{digitalocean_auth_token}}"
      register: terraform
      async: 1000
      poll: 0
    - name: Waiting for Infrastructure to be Deployed
      async_status:
        jid: "{{ terraform.ansible_job_id }}"
      register: terraform_result
      until: terraform_result.finished
      retries: 30
      delay: 10
    - name: Debug Terraform
      debug:
        var: terraform_result 
        verbosity: 1
    - name: Refreshing Inventory
      meta: refresh_inventory
    - name: Clearing gathered facts
      meta: clear_facts