- name: Build-Runners
  import_playbook: apollo-runners-build.yml
  when: runner_build_enabled|bool

- name: Deploy-Runners
  import_playbook: apollo-runners-deploy.yml
  when: runner_deploy_enabled|bool