# Create Staging/Production Managers and Workers
# Check if the provisioning succeeded
# Wait 100s for hosts to come up if they've been recently created/changed
- name: Create Swarm Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  user: root
  tasks:
    - name: Debug
      debug:
        msg: Item {{ item.location }}
      #loop: "{{ nodes.manager|dict2items }}"
      with_items: "{{ nodes.manager }}"

    - name: Remove Managers from Swarm Network
      hcloud_server_network:
        api_token: "{{ hcloud_token }}"
        network: swarm
        server: "{{ item.name }}"
        state: absent
      with_items: "{{ nodes.manager }}"
    - name: Remove 3 Volumes for each Node
      hcloud_volume:
        api_token: "{{ hcloud_token }}"
        name: "{{ item[0].name+'-'+item[1] }}"
        server: ""
        size: 50
        state: absent
        automount: no
      with_nested:
        - "{{ nodes.manager }}"
        - ["block-1", "block-2", "block-3"]
    - name: Remove Managers
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ item.name }}"
        server_type: cx41
        image: ubuntu-16.04
        location: "{{ item.location }}"
        ssh_keys:
          - MBio DevOps
        state: absent
        labels:
          swarm: ""
          manager: ""
          mbiosphere: ""
        backups: no
      with_items: "{{ nodes.manager }}"
    - name: Remove Workers from Swarm Network
      hcloud_server_network:
        api_token: "{{ hcloud_token }}"
        network: swarm
        server: "{{ item.name }}"
        state: absent
      with_items: "{{ nodes.worker }}"
    - name: Remove 3 Volumes for each Node
      hcloud_volume:
        api_token: "{{ hcloud_token }}"
        name: "{{ item[0].name+'-'+item[1] }}"
        server: "{{ item[0].name }}"
        size: 50
        state: absent
        automount: no
      with_nested:
        - "{{ nodes.worker }}"
        - ["block-1", "block-2", "block-3"]
    - name: Remove Workers
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ item.name }}"
        server_type: cx41
        image: ubuntu-16.04
        location: "{{ item.location }}"
        ssh_keys:
          - MBio DevOps
        state: absent
        labels:
          swarm: ""
          worker: ""
          mbiosphere: ""
        backups: no
      with_items: "{{ nodes.worker }}"
    - name: Remove Runners
      hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ item.name }}"
        server_type: cx11
        image: ubuntu-18.04
        location: "{{ item.location }}"
        ssh_keys:
          - MBio DevOps
        state: absent
        labels:
          runner: ""
          mbiosphere: ""
        backups: no
      with_items: "{{ nodes.runner }}"
    - name: Remove Swarm Subnet
      hcloud_subnetwork:
        api_token: "{{ hcloud_token }}"
        network: swarm
        ip_range: 10.0.0.0/16
        network_zone: eu-central
        type: server
        state: absent
    - name: Remove Swarm network
      hcloud_network:
        api_token: "{{ hcloud_token }}"
        name: swarm
        ip_range: 10.0.0.0/8
        state: absent
        labels:
          swarm: ""
          mbiosphere: ""
    
    # - name: Create staging-manager-1
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: staging-manager-1
    #     server_type: cx11
    #     image: ubuntu-18.04
    #     location: nbg1
    #     ssh_keys:
    #       - MBio DevOps
    #     state: present
    #     labels:
    #       type: swarm
    #       environment: staging
    #       role: manager
    #     backups: no
    #   register: server1
    # - name: Create staging-manager-2
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: staging-manager-2
    #     server_type: cx11
    #     image: ubuntu-18.04
    #     location: nbg1
    #     ssh_keys:
    #       - MBio DevOps
    #     state: present
    #     labels:
    #       type: swarm
    #       environment: staging
    #       role: manager
    #     backups: no
    #   register: server2
    # - name: Create staging-manager-3
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: staging-manager-3
    #     server_type: cx11
    #     image: ubuntu-18.04
    #     location: nbg1
    #     ssh_keys:
    #       - MBio DevOps
    #     state: present
    #     labels:
    #       type: swarm
    #       environment: staging
    #       role: manager
    #     backups: no
    #   register: server3
    # - name: Create staging-worker-1
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: staging-worker-1
    #     server_type: cx11
    #     image: ubuntu-18.04
    #     location: nbg1
    #     ssh_keys:
    #       - MBio DevOps
    #     state: present
    #     labels:
    #       type: swarm
    #       environment: staging
    #       role: worker
    #     backups: no
    #   register: server4
    # - name: Create staging-worker-2
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: staging-worker-2
    #     server_type: cx11
    #     image: ubuntu-18.04
    #     location: nbg1
    #     ssh_keys:
    #       - MBio DevOps
    #     state: present
    #     labels:
    #       type: swarm
    #       environment: staging
    #       role: worker
    #     backups: no
    #   register: server5
    # - name: Create staging-worker-3
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: staging-worker-3
    #     server_type: cx11
    #     image: ubuntu-18.04
    #     location: nbg1
    #     ssh_keys:
    #       - MBio DevOps
    #     state: present
    #     labels:
    #       type: swarm
    #       environment: staging
    #       role: worker
    #     backups: no
    #   register: server6
    # - name: Check staging-manager-1
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: "{{ server1.hcloud_server.name }}"
    #     state: started
    #   when: server1.changed
    # - name: Check staging-manager-2
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: "{{ server2.hcloud_server.name }}"
    #     state: started
    #   when: server2.changed
    # - name: Check staging-manager-3
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: "{{ server3.hcloud_server.name }}"
    #     state: started
    #   when: server3.changed
    # - name: Check staging-worker-1
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: "{{ server1.hcloud_server.name }}"
    #     state: started
    #   when: server4.changed
    # - name: Check staging-worker-2
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: "{{ server2.hcloud_server.name }}"
    #     state: started
    #   when: server5.changed
    # - name: Check staging-worker-3
    #   hcloud_server:
    #     api_token: "{{ hcloud_token }}"
    #     name: "{{ server3.hcloud_server.name }}"
    #     state: started
    #   when: server6.changed
    - name: Refresh inventory to ensure new instances exist in inventory
      meta: refresh_inventory
