---
- name: Debug Interfaces
  debug: 
    msg: "{{ 'Private Interface: '+private_iface+' - Public Interface: '+public_iface+' - Ingress IP: '+ingress_ip }}"

- name: Copying firewall config
  template:
    src: templates/iptables.conf.j2
    dest: /etc/iptables.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart firewall
  tags:
    - firewall

- name: Copying firewall service
  template:
    src: templates/iptables.service.j2
    dest: /etc/systemd/system/iptables.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd
  tags:
    - firewall

- name: Enabling firewall service
  service:
    name: iptables
    enabled: True
  tags:
    - firewall